name: Autobutler Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        type: string
        required: true
env:
  WORKING_DIR: ${{ github.workspace }}
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check tag format
        run: |
          if [[ ! "${{ inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag must be in the format vX.Y.Z"
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: autobutler-org/autobutler
          ref: ${{ inputs.tag }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: ~> v2
          args: release --clean
          workdir: ${{ env.WORKING_DIR }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: autobutler-release
          path: ${{ env.WORKING_DIR }}/dist/*
